language: rust
cache: cargo
rust:
  - stable
addons:
  apt:
    sources:
      - debian-sid
    packages:
      - dpkg
      - --allow-unauthenticated binaryen
before_script:
  - curl -sL https://deb.nodesource.com/setup_12.x | bash -
  - apt-get install -y nodejs
  - curl -s -L https://github.com/getzola/zola/releases/download/v0.6.0/zola-v0.6.0-x86_64-unknown-linux-gnu.tar.gz | sudo tar xvzf - -C /usr/local/bin
  - cargo install --force wasm-pack 
  - wasm-pack --version
  - cargo install --force tinysearch
  - tinysearch --version
script:
  - make build
after_success: |
  [ $TRAVIS_BRANCH = source ] &&
  [ $TRAVIS_PULL_REQUEST = false ] &&
  make build &&
  sudo pip install ghp-import &&
  ghp-import --no-jekyll \
            --cname=matthias-endler.de \
            --message="New release!" \
            --branch=master \
            public
  git push -fq https://${GH_TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git master